rosplan_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    # wp0: [0.0, 0.0, 0.0]   # Charger 1/ spawn
    # wp1: [-4.9, 2.7, 0.0]   # Charger 2
    # wp2: [0.9, 2.8, 0.7]    # Object 1
    # wp3: [-2.5, 6.7, 0.7]   # Object 2
    # wp4: [-5.5, 4.9, 2.2]  # Object 3
    # wp5: [-7.0, -0.5, -2.9]  # Object 4
    # wp6: [-2.4, -2.2, -0.8]  # Object 5
    # wp7: [2.3, -1.1, -0.8]  # Object 6        

    wp0: [0, 0, 0]   # Charger 1/ spawn
    wp6: [-0.16, 1.2, -3.14]   # Charger 2
    wp2: [1.40, 1.70, 1.7]    # Object 1
    wp3: [2.26, 0.20, -3.14]   # Object 2
    wp4: [2.6, 1.9, 1.7]  # Object 3
    wp5: [3.9, 0.45, -1.7]  # Object 4
    wp1: [3.7, 2.1, 1.73]  # Object 5